List<Map> countries = [
  {'name': "United Arab Emirates", 'cc': "ae"},
  {'name': "Argentina", 'cc': "ar"},
  {'name': "Austria", 'cc': "at"},
  {'name': "Australia", 'cc': "au"},
  {'name': "Belgium", 'cc': "be"},
  {'name': "Bulgaria", 'cc': "bg"},
  {'name': "Brazil", 'cc': "br"},
  {'name': "Canada", 'cc': "ca"},
  {'name': "Switzerland", 'cc': "ch"},
  {'name': "China", 'cc': "cn"},
  {'name': "Colombia", 'cc': "co"},
  {'name': "Czech Republic", 'cc': "cz"},
  {'name': "Germany", 'cc': "de"},
  {'name': "Egypt", 'cc': "eg"},
  {'name': "France", 'cc': "fr"},
  {'name': "United Kingdom", 'cc': "gb"},
  {'name': "Greece", 'cc': "gr"},
  {'name': "Hong Kong", 'cc': "hk"},
  {'name': "Hungary", 'cc': "hu"},
  {'name': "Indonesia", 'cc': "id"},
  {'name': "Ireland", 'cc': "ie"},
  {'name': "Israel", 'cc': "il"},
  {'name': "India", 'cc': "in"},
  {'name': "Italy", 'cc': "it"},
  {'name': "Japan", 'cc': "jp"},
  {'name': "South Korea", 'cc': "kr"},
  {'name': "Lithuania", 'cc': "lt"},
  {'name': "Latvia", 'cc': "lv"},
  {'name': "Morocco", 'cc': "ma"},
  {'name': "Mexico", 'cc': "mx"},
  {'name': "Malaysia", 'cc': "my"},
  {'name': "Nigeria", 'cc': "ng"},
  {'name': "Netherlands", 'cc': "nl"},
  {'name': "Norway", 'cc': "no"},
  {'name': "New Zealand", 'cc': "nz"},
  {'name': "Philippines", 'cc': "ph"},
  {'name': "Poland", 'cc': "pl"},
  {'name': "Portugal", 'cc': "pt"},
  {'name': "Romania", 'cc': "ro"},
  {'name': "Serbia", 'cc': "rs"},
  {'name': "Russia", 'cc': "ru"},
  {'name': "Saudi Arabia", 'cc': "sa"},
  {'name': "Singapore", 'cc': "sg"},
  {'name': "Slovenia", 'cc': "si"},
  {'name': "Slovakia", 'cc': "sk"},
  {'name': "Thailand", 'cc': "th"},
  {'name': "Turkey", 'cc': "tr"},
  {'name': "Taiwan", 'cc': "tw"},
  {'name': "Ukraine", 'cc': "ua"},
  {'name': "United States", 'cc': "us"},
  {'name': "Venezuela", 'cc': "ve"},
  {'name': "South Africa", 'cc': "za"},
];
